name: Pelican site CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Pages Pelican Build Action
    - uses: nelsonjchen/gh-pages-pelican-action@0.1.10
      with:
        GH_PAGES_BRANCH: gh-pages
        GH_PAGES_CNAME: https://josephcourtney.com
        PELICAN_CONFIG_FILE: pelicanconf.py
        PELICAN_CONTENT_FOLDER: content
        PELICAN_THEME_FOLDER: theme
